/* 
    LEGENED http://climateviewer.net/
    var layerId = l.I,
    format = l.F,
    geoDataSrc = l.G,
    geoLayers = l.L,
    source = l.S,
    sourceUrl = l.U,
    zoom = l.Z,
    markerImg = l.MI,
    markerLabel = l.ML,
    markerScale = l.MS,
    markerMod = l.M,
    largeLayer = l.H,
    newLayer = l.NL,
    timeline = l.C,
    proxy = l.P;
*/
var layers = {
    I: 'Climate-Viewer',
    Live: { N: "Live Alerts",
        Earthquake: { N: "Earthquake", icon: "rss", '>': [
            { I: "usgs-all-hour", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - All Earthquakes (Last Hour)"},
            //{ I: "usgs-big-today", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_day.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - Significant Earthquakes (Today)"},
            { I: "usgs-45-today", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - M4.5+ Earthquakes (Today)"},
            { I: "usgs-25-today", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - M2.5+ Earthquakes (Today)"},
            { I: "usgs-all-today", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - All Earthquakes (Today)"},
            //{ I: "usgs-big-7day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - Significant Earthquakes (Last Week)"},
            { I: "usgs-45-7day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - M4.5+ Earthquakes (Last Week)"},
            { I: "usgs-25-7day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - M2.5+ Earthquakes (Last Week)"},
            { I: "usgs-all-7day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - All Earthquakes (Last Week)"},
            //{ I: "usgs-big-30day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_month.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - Significant Earthquakes (Last Month)"},
            { I: "usgs-45-30day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_month.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - M4.5+ Earthquakes (Last Month)"},
            { I: "usgs-25-30day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_month.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - M2.5+ Earthquakes (Last Month)"},
            { I: "usgs-all-30day", T: 'geojson', ML: "usgs-eq", MI: "http://climateviewer.com/gallery/earthquakes.png", G: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.geojson", S: "United States Geological Society (USGS) Earthquake Hazards Program", U: "http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", N: "USGS - All Earthquakes (Last Month)"},
            { I: "kml-emsc", T: 'kml', P: true, G: "http://www.emsc-csem.org/Earthquake/Map/earth/kml.php", S: "Centre Sismologique Euro-Méditerranéen (CSEM) Euro-Med earthquakes", U: "http://www.emsc-csem.org/", N: "Euro-Med Earthquakes - CSEM/EMSC"},
            { P: true, I: "kml-buoy", T: 'kml', G: "http://www.ndbc.noaa.gov/kml/marineobs_as_kml.php?sort=owner", S: "National Oceanic and Atmospheric Administration (NOAA) National Data Buoy Center", U: "http://www.ndbc.noaa.gov/", N: "NOAA Buoys"}
        ]},
        Volcano: { N: "Volcano", icon: "warning sign", '>': [
            { I: "kml-volcano", P: true, M: true, T: 'kml', G: "http://www.volcano.si.edu/news/WeeklyVolcanoGE-Reports.kmz", S: "Smithsonian Institute National Museum of History, Global Volcanism Program: Latest Volcanic Activity", U: "http://www.volcano.si.edu/", N: "Weekly Activity and Eruptions"},
            { I: "gvp-volcanos", T: 'geojson', G: "/layers/geojson/gvp-volcanos-cv3d.geojson", MI: "/img/icons/volcano.png", S: "Smithsonian Institute National Museum of History, Global Volcanism Program", U: "http://www.volcano.si.edu/", N: "Global Vocanoes"}
        ]},
        Fire: { N: "Fire", icon: "fire", '>': [
            { I: "kml-usda-fire", Z: true, T: 'kml', P: true, G: "http://activefiremaps.fs.fed.us/data/kml/conus.kmz", S: "US Department of Agriculture (USDA) Forest Service Remote Sensing Applications Center, Active Fire Mapping Program", U: "http://activefiremaps.fs.fed.us/", N: "Active Fire Mapping Program"},
            { I: "kml-noaa-fire", T: 'kml', P: true, G: "http://www.ospo.noaa.gov/data/land/fire/fire.kml", S: "National Oceanic and Atmospheric Administration (NOAA) Hazard Mapping System Fire and Smoke Product", U: "http://www.ospo.noaa.gov/Products/land/hms.html", N: "NOAA HMS Fire"},
            { I: "kml-noaa-smoke", T: 'kml', P: true, G: "http://www.ospo.noaa.gov/data/land/fire/smoke.kml", S: "National Oceanic and Atmospheric Administration (NOAA) Hazard Mapping System Fire and Smoke Product", U: "http://www.ospo.noaa.gov/Products/land/hms.html", N: "NOAA HMS Smoke"}
        ]},
        FEMA: { N: "FEMA", icon: "emergency", '>': [
            { I: "wms-femad", T: 'wms', G: "http://gis.fema.gov/SOAP//FEMA/DECs/MapServer/WMSServer", L: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25", S: "Federal Emergency Management Agency (FEMA)", U: "http://gis.fema.gov/DataFeeds.html", N: "FEMA Current Disaster Declarations"},
            { I: "wms-femah", T: 'wms', G: "http://gis.fema.gov/SOAP//FEMA/HistoricalDesignations/MapServer/WMSServer", L: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25", S: "Federal Emergency Management Agency (FEMA)", U: "http://gis.fema.gov/DataFeeds.html", N: "FEMA Historical Disaster Declarations"},
            { I: "wms-femar", T: 'wms', G: "http://gis.fema.gov/SOAP//FEMA/RegHQs/MapServer/WMSServer", L: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25", S: "Federal Emergency Management Agency (FEMA)", U: "http://gis.fema.gov/DataFeeds.html", N: "FEMA Regions and Field Offices"},
            { I: "wms-femae", T: 'wms', G: "http://gis.fema.gov/SOAP//FEMA/EvacRoutes/MapServer/WMSServer", L: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25", S: "Federal Emergency Management Agency (FEMA)", U: "http://gis.fema.gov/DataFeeds.html", N: "FEMA Hurricane Evacuation Routes"}
        ]},
        alerts: {  N: "Weather Alerts", icon: "cloud", '>': [
            { P: true, I: "kml-nwshlog", T: 'kml', M: true, MI: "http://climateviewer.com/gallery/lightning_bolt.png", G: "http://wdssii.nssl.noaa.gov/geotiff/kml/NwsHourlyStormLogs.kml", S: "NOAA National Severe Storms Laboratory, Warning Decision Support System - Integrated Information (WDSS-II)", U: "http://wdssii.nssl.noaa.gov/", N: "Hourly Storm Log"},
            { P: true, I: "kml-nwsdlog", T: 'kml', M: true, MI: "http://climateviewer.com/gallery/lightning_bolt.png", G: "http://wdssii.nssl.noaa.gov/geotiff/kml/NwsDailyStormLogs.kml", S: "NOAA National Severe Storms Laboratory, Warning Decision Support System - Integrated Information (WDSS-II)", U: "http://wdssii.nssl.noaa.gov/", N: "Daily Storm Log"},
            { P: true, I: "kml-hurrgdacs", T: 'kml', G: "http://www.gdacs.org/xml/gdacs.kml", S: " Global Disaster Alert and Coordination System (GDACS)", U: "http://www.gdacs.org/", N: "Hurricane Tracker (GDACS)"},
            { I: "nhc-hurricane", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/wwa", L: "NHC_TRACK_POLY,NHC_TRACK_LIN,NHC_TRACK_PT,NHC_TRACK_WWLIN,NHC_TRACK_PT_72DATE,NHC_TRACK_PT_120DATE,NHC_TRACK_PT_0NAMEDATE,NHC_TRACK_PT_MSLPLABELS,NHC_TRACK_PT_72WLBL,NHC_TRACK_PT_120WLBL,NHC_TRACK_PT_72CAT,NHC_TRACK_PT_120CAT", S: "NOAA Ocean Service's nowCOAST's Map Services - National Weather Service - National Hurricane Center's Tropical Cyclone Track Forecast", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Hurricane and Tropical Cyclone Track Forecast"},
            { I: "nws-tstorm", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/wwa", L: "WARN_SHORT_SVR,WARN_SHORT_EWW,WARN_SHORT_TOR,WARN_SHORT_FLW,WARN_SHORT_FFW,WARN_SHORT_SMW", S: "NOAA Ocean Service's nowCOAST's Map Services - National Weather Service - Short-Duration Storm-Based Severe Tornado, Wind, Thunderstorm, Flood, and Marine Warning Polygons", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Severe Weather Watches and Warnings"}
        ]},
        clouds: { N: "Clouds", icon: "cloud", '>': [
            { I: "kml-clouds", T: 'kml', G: "http://mw1.google.com/mw-weather/clouds/root.kmz", S: "<p>U.S. Naval Research Laboratory (NRL) Marine Meteorology Division.</p><p>Since the 1960s, the capability to view Earth's cloud patterns from space has been made possible from two main types of environmental satellites, geostationary Earth-orbiting and low Earth-orbiting satellites. At least five geostationary satellites positioned around the equator are capable of providing depictions of global weather patterns, updated every hour. From their vantage point 36,000 km above the equator, the sensors onboard geostationary satellites can't quite 'see'the very high latitudes near the north and south poles. Since their orbit flies over the high latitude regions over the north and south poles typically every 90 minutes, low Earth-orbiting satellite imagery is well-suited to complement the geostationary imagery and thereby provide total global coverage. Even so, such satellite data merging is complicated by the fact that each individual satellite observation represents a single 'snapshot' of the cloud patterns, each taken at slightly different times, whereas the underlying clouds themselves are constantly moving and evolving.</p><p>In this depiction of global clouds, these satellite data are processed to discriminate clear (transparent) and cloudy areas. For cloudy areas, the brightness is approximated based upon the cloud top temperature relative to the surface temperature, as a proxy for the height of each cloud pixel. Due their location near the Earth's surface, low level clouds such as stratocumulus and stratus (fog) clouds may be poorly represented.</p>", U: "http://www.nrlmry.navy.mil/", N: "Global Clouds - NRL"},
            { P: true, I: "kml-usnmsir", T: 'kml', G: "/layers/kml/3rdparty/weather/clouds/USN-multisat-ir-CVDB.kmz", S: "Image S: US. Naval Research Laboratory, Marine Meteorology Division. Google Earth overlay by Jim Lee", U: "http://www.nrlmry.navy.mil/archdat/global/stitched/ir/", N: "Infrared Clouds - NRL"},
            { I: "wms-goes-vis", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "RAS_GOES", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD - Visible Satellite Cloud Imagery", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "GOES Visible Satellite Cloud Imagery"},
            { I: "wms-goes-ir", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "RAS_GOES_I4", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD - Infrared Satellite Cloud Imagery", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "GOES Infrared Satellite Cloud Imagery"}
        ]},
        radar: { N: "Radar", icon: "cloud", '>': [
            { I: "mesonet-nexrad", T: 'wms', G: "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0q.cgi", L: "nexrad_base_reflect", S: "Iowa State University of Science and Technology MESONET", U: "http://mesonet.agron.iastate.edu/ogc/", N: "NEXRAD Base Reflectivity"},
            { I: "wms-nexrad", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "RAS_RIDGE_NEXRAD", S: "NOAA Ocean Service's nowCOAST's Map Services - National Weather Service - NEXRAD Doppler Radar Mosaic for CONUS (Continental USA), Puerto Rico, Hawaii, Alaska and Guam", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "NWS RIDGE NEXRAD Radar"},
            { P: true, I: "kml-wxanalyst", T: 'kml', G: "http://wxanalyst.com/radar/WxAnalyst_NEXRAD.kmz", S: "WxAnalyst", U: "http://wxanalyst.com/radar/", N: "WxAnalyst NEXRAD"},
            { I: "f142", Z: true, T: 'kml', G: "/layers/kml/places/North-American-Doppler-Radar-CV3D.kmz", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/rezn8d/", N: "North American Doppler Radar Stations"}
        ]},
        ra: { N: "Radar Animations", icon: "cloud", '>': [
            { P: true, I: "kml-nexradcgl", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/centgrtlakes_N0R_loop.kml", S: "Central Great Lakes - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "Central Great Lakes"},
            { P: true, I: "kml-nexradne", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/northeast_N0R_loop.kml", S: "North East - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "North East"},
            { P: true, I: "kml-nexradnr", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/northrockies_N0R_loop.kml", S: "North Rockies - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "North Rockies"},
            { P: true, I: "kml-nexradpnw", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/pacnorthwest_N0R_loop.kml", S: "Pacific North West - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "Pacific North West"},
            { P: true, I: "kml-nexradpsw", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/pacsouthwest_N0R_loop.kml", S: "Pacific South West - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "Pacific South West"},
            { P: true, I: "kml-nexradse", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/southeast_N0R_loop.kml", S: "South East - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "South East"},
            { P: true, I: "kml-nexradsmv", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/southmissvly_N0R_loop.kml", S: "South Mississippi Valley - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "South Mississippi Valley"},
            { P: true, I: "kml-nexradsp", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/southplains_N0R_loop.kml", S: "South Plains - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "South Plains"},
            { P: true, I: "kml-nexradsr", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/southrockies_N0R_loop.kml", S: "South Rockies - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "South Rockies"},
            { P: true, I: "kml-nexradumv", Z: true, T: 'kml', G: "http://radar.weather.gov/ridge/kml/animation/sectors/uppermissvly_N0R_loop.kml", S: "Upper Mississippi Valley - NEXRAD WSR-88D (Weather Surveillance Radar - 1988 Doppler). Latest 2 hour animation", U: "http://radar.weather.gov/ridge/", N: "Upper Mississippi Valley"}
        ]},
        surface: { N: "Surface Observations", icon: "cloud", '>': [
            { I: "metar-temp", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MET_TEMP", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Surface Air Temperature point observations (degrees Fahrenheit)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Surface Air Temperature"},
            { I: "metar-dp", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MET_DP", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Dewpoint Temperature point observations (degrees Fahrenheit)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Dewpoint Temperature"},
            { I: "metar-wind", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MET_WIND", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Wind Velocity (Speed & Direction) point observations (Knots)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Wind Speed & Direction"},
            { I: "metar-pressure", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MET_PRES", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Mean Sea Level Pressure point observations (millibars)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Mean Sea Level Pressure"},
            { I: "metar-vis", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MET_VIS", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Visibility point observations (miles)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Visibility"},
            { I: "metar-sea-temp", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MAR_SSTF", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Sea Surface Temperature point observations (degrees Fahrenheit)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Sea Surface Temperature"},
            { I: "metar-wave-height", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MAR_SWHFT", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Significant Wave Height point observations (feet)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Significant Wave Height"},
            { I: "metar-id", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "OBS_MET_ID", S: "NOAA Ocean Service's nowCOAST's Map Services - NESDIS/OSDPD & OAR/MADIS Group - Ientifier for Meteorological/Oceanographic Observing Station", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "METAR Station I"}
        ]},
        rain: { N: "Precipitation", icon: "umbrella", ">": [
            { P: true, I: "kml-usdrought", T: 'kml', G: "http://torka.unl.edu:8080/dm/data/kml/current/usdm_current.kmz", S: "University of Nebraska-Lincoln, US. Drought Monitor", U: "http://droughtmonitor.unl.edu/", N: "US. Drought Monitor"},
            { P: true, I: "kml-usshour", T: 'kml', G: "http://www.wpc.ncep.noaa.gov/kml/qpf/QPF6hr_f00-f06_latest.kml", S: "NOAA National Weather Service, Weather Prediction Center, HPC Quantitative Precipitation Forecasts (QPFs)", U: "http://www.wpc.ncep.noaa.gov/", N: "US. 6-hour Forecast"},
            { P: true, I: "kml-usstfhour", T: 'kml', G: "http://www.wpc.ncep.noaa.gov/kml/qpf/QPF24hr_Day1_main.kml", S: "NOAA National Weather Service, Weather Prediction Center, HPC Quantitative Precipitation Forecasts (QPFs)", U: "http://www.wpc.ncep.noaa.gov/", N: "US. 24-hour Forecast"},
            { P: true, I: "kml-ussfd", T: 'kml', G: "http://www.wpc.ncep.noaa.gov/kml/qpf/QPF120hr_Day1-5_latest.kml", S: "NOAA National Weather Service, Weather Prediction Center, HPC Quantitative Precipitation Forecasts (QPFs)", U: "http://www.wpc.ncep.noaa.gov/", N: "US. 5-day Forecast"},
            { P: true, I: "kml-ussfdflood", T: 'kml', G: "http://www.wpc.ncep.noaa.gov/kml/fop/fop.kml", S: "NOAA National Weather Service, Weather Prediction Center, 5-Day Significant River Flood Outlook", U: "http://www.wpc.ncep.noaa.gov/", N: "US. Significant Flood Risk"},
            { P: true, H: true, I: "kml-usfloods", T: 'kml', G: "http://water.weather.gov/ahps/worldfiles/ahps_national_fcst.kmz", S: "NOAA National Weather Service, River Observations", U: "http://water.weather.gov/ahps/", N: "US. River Flood Levels"},
            { P: true, I: "kml-trmmgf", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/trmm_google_hydro_model_b.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/publications_dir/potential_flood_hydro.html", N: "Global Flood Forecast"},
            { P: true, I: "kml-trmmgff", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/trmm_google_G5_extended_hydro_model.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/publications_dir/potential_flood_hydro.html", N: "5-day Flood Forecast"},
            { P: true, I: "kml-trmmthr", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/3B42_rain_accumulation_3hr.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/", N: "3-hour Accumulated Rainfall"},
            { P: true, I: "kml-trmmtfhr", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/3B42_rain_accumulation_24hr_b.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/", N: "24-hour Accumulated Rainfall"},
            { P: true, I: "kml-trmmsthr", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/3B42_rain_accumulation_72hr_b.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/", N: "72-hour Accumulated Rainfall"},
            { P: true, I: "kml-trmmosehr", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/3B42_rain_accumulation_168hr_b.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/", N: "168-hour Accumulated Rainfall"},
            { P: true, I: "kml-trmmav", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/30_day_average.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/", N: "30-day Average Rainfall"},
            { P: true, I: "kml-trmman", T: 'kml', G: "http://trmm.gsfc.nasa.gov/trmm_rain/Events/30_day_anomaly.kml", S: "NASA Tropical Rainfall Measuring Mission (TRMM)", U: "http://trmm.gsfc.nasa.gov/", N: "30-day Anomaly Rainfall"},
            { P: true, I: "kml-eumetod", T: 'kml', G: "http://oiswww.eumetsat.int/IPPS/html/GE/MET0D_VP-MPE.kml", S: "European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT) Meteosat 0 degree Multi-Sensor Precipitation Estimate (MPE) ", U: "http://www.eumetsat.int/website/home/Data/Products/index.html", N: "Meteosat METOD"},
            { P: true, I: "kml-euiodc", T: 'kml', G: "http://oiswww.eumetsat.int/IPPS/html/GE/IODC_VP-MPE.kml", S: "European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT) Meteosat IODC Multi-Sensor Precipitation Estimate (MPE) ", U: "http://www.eumetsat.int/website/home/Data/Products/index.html", N: "Meteosat IODC"},
            { P: true, I: "kml-usdanrcs", T: 'kml', G: "http://www.wcc.nrcs.usda.gov/ftpref/data/water/wcs/earth/snotelwithoutlabels.kmz", S: "USDA Natural ReSs Conservation Service (NRCS)", U: "http://www.wcc.nrcs.usda.gov/", N: "SNOTEL Snowfall Monitors"},
            { P: true, I: "kml-nohrsc", T: 'kml', G: "http://www.nohrsc.noaa.gov/snow_model/GE/latest_nohrsc_nsm.kmz", S: "National Weather Service, National Operational Hydrologic Remote Sensing Center (NOHRSC)", U: "http://www.nohrsc.noaa.gov/", N: "NOHRSC Snowfall Monitors"}
        ]},
        Report: {  N: "Climate Viewer Reports", icon: "bullhorn", '>': [
            { I: "cvr01", T: 'geojson', M: true, MS: "2", G: "/layers/geojson/cvreports-cv3d.geojson", MI: "/img/cv3d-red.png", S: "Climate Viewer Reports", U: "https://climateviewer.crowdmap.com/", N: "CV Reports - 2011 - 2015"}
        ]}
    },
    satellites: { N: "Satellites",
        sat: { N: "Satellite Imagery", icon: "globe", '>': [
            { I: "MODIS_Terra_CorrectedReflectance_TrueColor", T: 'nasa-gibs', S: "NASA Earth Observing System Data and Information System (EOSDIS) Global Imagery Browse Service (GIBS)", U: "https://earthdata.nasa.gov/", N: "Corrected Reflectance (True Color)"},
            { I: "MODIS_Terra_CorrectedReflectance_Bands721", T: 'nasa-gibs', S: "NASA Earth Observing System Data and Information System (EOSDIS) Global Imagery Browse Service (GIBS)", U: "https://earthdata.nasa.gov/", N: "Corrected Reflectance (Bands 7-2-1)"},
            { I: "MODIS_Terra_CorrectedReflectance_Bands367", T: 'nasa-gibs', S: "NASA Earth Observing System Data and Information System (EOSDIS) Global Imagery Browse Service (GIBS)", U: "https://earthdata.nasa.gov/", N: "Corrected Reflectance (Bands 3-6-7)"},
            { I: "MODIS_Terra_SurfaceReflectance_Bands121", T: 'nasa-gibs', S: "NASA Earth Observing System Data and Information System (EOSDIS) Global Imagery Browse Service (GIBS)", U: "https://earthdata.nasa.gov/", N: "Land Surface Reflectance (Bands 1-2-1)"}
        ]},
        satAnimation: { N: "Satellite Animations", icon: "globe", '>': [
            { P: true, C: true, I: "sat15", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/tpw/TPW.natl.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "North Atlantic - Total Precipitable Water"},
            { P: true, C: true, I: "sat16", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/tpw/TPW.epac.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "North East Pacific - Total Precipitable Water"},
            { P: true, C: true, I: "sat17", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/tpw/TPW.wpac.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "North West Pacific - Total Precipitable Water"},
            { P: true, C: true, I: "sat18", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/tpw/TPW.indo.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "Indian Ocean - Total Precipitable Water"},
            { P: true, C: true, I: "sat19", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/tpw/TPW.ausf.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "Western Australia - Total Precipitable Water"},
            { P: true, H: true, C: true, I: "sat09", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/mosaic/movies/kml/tiles/RT.mosaic.mosaiceir.tiles.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "East North Atlantic Region - Infrared"},
            { P: true, H: true, C: true, I: "sat10", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/mosaic/movies/kml/tiles/RT.mosaic.mosaicewv.tiles.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "North Atlantic Region - Water Vapor"},
            { P: true, H: true, C: true, I: "sat11", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/mosaic/movies/kml/tiles/RT.mosaic.mosaicwir.tiles.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "North Pacific Region - Infrared"},
            { P: true, H: true, C: true, I: "sat12", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/mosaic/movies/kml/tiles/RT.mosaic.mosaicwwv.tiles.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "North Pacific Region - Water Vapor"},
            { P: true, H: true, C: true, I: "sat13", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/mosaic/movies/kml/tiles/RT.mosaic.mosaicsir.tiles.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "South Pacific Region - Infrared"},
            { P: true, H: true, C: true, I: "sat14", T: 'kml', G: "http://tropic.ssec.wisc.edu/real-time/mosaic/movies/kml/tiles/RT.mosaic.mosaicswv.tiles.kml", S: "CIMSS/SSEC University of Wisconsin-Madison", U: "http://tropic.ssec.wisc.edu/", N: "South Pacific Region - Water Vapor"}
        ]}
    },
    pollution: { N: "Pollution",
        fossilfuel: { N: "Fossil Fuel", icon: "recycle sign", '>': [
            { H: true, T: 'geojson', MS: 3, MI: 'http://climateviewer.com/gallery/oil_well.png', I: "p07", G: "/layers/geojson/Fracking-Chemical-Reports-cv3d.geojson", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://blog.skytruth.org/2012/11/skytruth-releases-fracking-chemical.html", N: "Fracking America"},
            { C: true, Z: true, I: "nrdc-drinking-water-impacts", T: 'kml', G: "/layers/kml/3rdparty/pollution/NRDC-drinking-water-impacts-2011-CV3D.kmz", S: "National Resource Defense Coalition", U: "http://www.fractracker.org/downloads/nrdc-list-of-suspected-drinking-water-impacts-2011/", N: "NRDC Drinking Water Impacts 2011"},
            { I: "coal-power-now", Z: true, T: 'geojson', MS: 3, MI: 'http://climateviewer.com/gallery/smoke-red.png', G: "/layers/geojson/Contaminated-Coal-Waste-NRDC-current-factories-cv3d.geojson", S: "Natural ReSs Defense Council (NRDC) “Power plants produce about 130 million tons of contaminated waste every year, and the federal government has failed to regulate it.” Across the nation, coal-fired power plants aren’t just polluting our skies and water. Each year, they generate millions of tons of waste contaminated with toxic metals -- more than two-thirds of which is dumped into landfills, storage ponds or old mines or otherwise stored somewhere, just waiting for disaster to strike.<br><br>More than four hundred forty existing coal-fired power plants in 47 states produced over 126 million tons of coal waste in 2005, contaminated by over 91 thousand tons of toxic metals. This table lists totals by state, ranked by total coal waste per state.", U: "http://www.nrdc.org/energy/coalwaste", N: "Coal Power Plants (current)"},
            { I: "coal-power-future", Z: true, T: 'geojson', MS: 3, MI: 'http://climateviewer.com/gallery/smoke-grey.png', G: "/layers/geojson/Contaminated-Coal-Waste-NRDC-future-factories-cv3d.geojson", S: "Natural ReSs Defense Council (NRDC) “Power plants produce about 130 million tons of contaminated waste every year, and the federal government has failed to regulate it.” Across the nation, coal-fired power plants aren’t just polluting our skies and water. Each year, they generate millions of tons of waste contaminated with toxic metals -- more than two-thirds of which is dumped into landfills, storage ponds or old mines or otherwise stored somewhere, just waiting for disaster to strike.<br><br>More than eighty new coal-fired power plants have been proposed around the country. If built, the plants will annually produce nearly 18 million tons of coal ash, contaminated by over 18 thousand tons of toxic metals. Over the course of their operating lives, these new power plants will produce approximately one billion tons of coal ash, with a million tons of toxic metals.", U: "http://www.nrdc.org/energy/coalwaste", N: "Coal Power Plants (future)"},
            { I: "coal-ash", Z: true, T: 'geojson', MS: 3, MI: 'http://climateviewer.com/gallery/mryuk.png', G: "/layers/geojson/Coal-Ash-Ponds-cv3d.geojson", S: "Natural ReSs Defense Council (NRDC) “The horror is unimaginable.  A community suffering severe health effects, with more than a thousand resIents blaming coal ash contamination for causing their sickness, including grisly birth defects in their children.”", U: "http://switchboard.nrdc.org/blogs/rperks/coal_ash_wreaking_havoc_on_hea.html", N: "Coal Ash in Ponds"},
            { I: "us-shale-gas", Z: true, T: 'kml', G: "/layers/kml/pollution/Shale-Gas-Basins-CV3D.kmz", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/rezn8d/", N: "Shale Gas Basins"},
            { H: true, I: "p08", Z: true, T: 'kml', G: "/layers/kml/pollution/cavern-field-Etzel-Germany-CV3D.kmz", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://www.bi-lebensqualität.de/", N: "Cavern Field, Etzel, Germany"},
            { I: "methane-release", T: 'geojson', G: "/layers/geojson/drilling-methane-release-cv3d.geojson", MS: "6", MI: "http://climateviewer.com/gallery/firedept.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/2014/04/01/haarp-lucy-sky-diamonds/", N: "Drilling Wells and Methane Release"},
            { I: "fracking-alaska", Z: true, T: 'geojson', G: "/layers/geojson/fracking-alaska-cv3d.geojson", MS: "6", MI: "http://climateviewer.com/gallery/oil_well.png", S: "Gas Hydrate Prospecting Using Well Cuttings and Mud-Gas Geochemistry from 35 Wells, North Slope, Alaska. Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://pubs.usgs.gov/sir/2011/5195/sir2011-5195_text.pdf", N: "Fracking Alaska"},
            { I: "oil-spills", T: 'geojson', G: "/layers/geojson/black-tides-oil-spills-cv3d.geojson", MI: "/img/icons/oil-well.png", S: "David Tryse's Google Earth files", U: "http://earth.tryse.net/", N: "Black Tides: Worst Oil Spills in History"}
        ]},
        nuclear: { N: "Nuclear", icon: "recycle sign", '>': [
            { I: "bw-reactor", T: 'geojson', G: "/layers/geojson/nuclear-bw-reactor-cv3d.geojson", MI: "/img/icons/nuke-red.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>., based on the work of Declan Butler.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "Boiling Water Reactors"},
            { I: "pw-reactor", T: 'geojson', G: "/layers/geojson/nuclear-pw-reactor-cv3d.geojson", MI: "/img/icons/nuke-green.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>., based on the work of Declan Butler.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "Pressurized Water Reactors"},
            { I: "phw-reactor", T: 'geojson', G: "/layers/geojson/nuclear-phw-reactor-cv3d.geojson", MI: "/img/icons/nuke-dkblue.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>., based on the work of Declan Butler.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "Pressurized Heavy Water Reactors"},
            { I: "lwg-reactor", T: 'geojson', G: "/layers/geojson/nuclear-lwg-reactor-cv3d.geojson", MI: "/img/icons/nuke-yellow.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>., based on the work of Declan Butler.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "Light Water Graphite Reactors"},
            { I: "gc-reactor", T: 'geojson', G: "/layers/geojson/nuclear-gc-reactor-cv3d.geojson", MI: "/img/icons/nuke-blue.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>., based on the work of Declan Butler.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "Gas Cooled Reactors"},
            { I: "other-reactor", T: 'geojson', G: "/layers/geojson/nuclear-other-reactor-cv3d.geojson", MI: "/img/icons/nuke-purple.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>., based on the work of Declan Butler.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "Other Reactors"},
            { H: true, I: "nuke-war", T: 'geojson', G: "/layers/geojson/nuclear-test-explosions-cv3d.geojson", MI: "/img/icons/nuke-boom.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>., based on the work of Wm. Robert Johnston and Lyle McElhaney", U: "http://climateviewer.com/nuclear-reactor-map/", N: "Nuclear Test Explosions"},
            { I: "radioactive-topten", T: 'kml', G: "/layers/kml/pollution/nuclear/Ten-Most-Radioactive-Locations-On-Earth-CV3D.kmz", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/2013/11/24/10-most-radioactive-places-on-earth/", N: "Ten Most Radioactive Places on Earth"},
            { I: "hibakusha", T: 'geojson', G: "/layers/geojson/hibakusha-worldwide-cv3d.geojson", MI: "/img/icons/nuke.png", S: "Dr. Alex Rosen, Hibakusa 'explosion-affected people' Worldwide", U: "http://www.ippnw-students.org/Japan/hibakushamap.html", N: "50 Nuclear Nightmares (Hibakusha Worldwide)"},
            { I: "tmi-meltdown", Z: true, T: 'geojson', G: "/layers/geojson/three-mile-island-meltdown-cv3d.geojson", MI: "/img/icons/nuke.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "1979 Three Mile Island Meltdown"},
            { I: "tmi-fallout", Z: true, T: 'kml', G: "/layers/kml/pollution/nuclear/Three-Mile-Island-meltdown-cv3d.kmz", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "1979 Three Mile Island Fallout"},
            { I: "chernobyl-meltdown", Z: true, T: 'kml', G: "/layers/kml/pollution/nuclear/Chernobyl-meltdown-Climate-Viewer-3D.kmz", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "1986 Chernobyl Meltdown"},
            { I: "chernobyl-fallout-fallout", Z: true, T: 'kml', G: "/layers/kml/pollution/nuclear/Chernobyl-meltdown-fallout-Climate-Viewer-3D.kmz", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/nuclear-reactor-map/", N: "1986 Chernobyl Fallout"},
            { I: "fukushima-meltdown", Z: true, T: 'kml', G: "/layers/kml/pollution/nuclear/Fukushima-Daiichi-meltdown-Climate-Viewer-3D.kmz", S: "Created July 4, 2013 by Jim Lee", U: "http://climateviewer.com/nuclear-reactor-map/", N: "2011 Fukushima-Daiichi Meltdown"},
            { I: "fukushima-fallout", Z: true, T: 'kml', G: "/layers/kml/pollution/nuclear/Fukushima-Daiichi-meltdown-fallout-Climate-Viewer-3D.kmz", S: "Created July 4, 2013 by Jim Lee", U: "http://climateviewer.com/nuclear-reactor-map/", N: "2011 Fukushima-Daiichi Fallout"},
            { P: true, I: "fuku-tsunami", Z: true, T: 'kml', G: "http://nctr.pmel.noaa.gov/honshu20110311/honshu_tsunami_2011-03-11.kmz", S: "NOAA Center for Tsunami Research, Maximum amplitude plot for Google Earth (KMZ)", U: "http://nctr.pmel.noaa.gov/honshu20110311/index.html", N: "2011 Fukushima Tsunami Wave Height"},
            { C: true, I: "honeywell-uf6", Z: true, T: 'kml', G: "/layers/kml/pollution/nuclear/Honeywell-Uranium-Hexafluoride-Release-10-27-2014-CV3D.kmz", S: "Did Metropolis get Nuked last night?? Radiation Release 10-27-2014", U: "http://climateviewer.com/2014/10/27/metropolis-get-nuked-last-night-2/", N: "2014 Honeywell UF6 Processing Facility Radiation Release"}
        ]},
        toxicrelease: { N: "Toxic Release", H: true, icon: "warning sign", '>': [
            { I: "epa-tri", H: true, T: 'geojson', MI: 'http://climateviewer.com/gallery/mryuk.png', G: "/layers/geojson/EPA-TRI-2011-cv3d.geojson", S: "2011 data, US Environmental Protection Agency (EPA) .KML file, converted to GeoJSON by Jim Lee", U: "http://www.epa.gov/enviro/facts/tri/index.html", N: "EPA Toxic Release Inventory (TRI) USA"}
        ]},
        toxicwaste: { N: "U.S. EPA Superfund Sites", icon: "recycle sign", H: true, '>': [
            { H: true, Z: true, I: "epa01", T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_01.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 1 - ME NH VT MA RI CT"},
            { H: true, I: "epa02", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_02.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 2 - NY NJ PR VI"},
            { H: true, I: "epa03", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_03.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 3 - PA DE DC MD VA WV"},
            { H: true, I: "epa04", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_04.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 4 - KY TN NC SC MS AL GA FL"},
            { H: true, I: "epa05", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_05.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 5 - MN WI IL MI IN OH"},
            { H: true, I: "epa06", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_06.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 6 - NM TX OK AR LA"},
            { H: true, I: "epa07", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_07.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 7 - NE KS IA MO"},
            { H: true, I: "epa08", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_08.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 8 - MT ND WY SD UT CO"},
            { H: true, I: "epa09", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_09.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 9 - CA NV AZ HI"},
            { H: true, I: "epa10", Z: true, T: 'kml', G: "/layers/kml/3rdparty/pollution/superfund/region_10.kmz", S: "EPA Superfund", U: "http://www.epa.gov/superfund/index.htm", N: "Region 10 - WA OR I AK"}
        ]},
        geoengineering: { N: "Weather Control", icon: "plane", '>': [
            //{ I: "p04", T: 'kml', G: "/layers/kml/pollution/ETC-Group-Geoengineering-CV3D.kmz", S: "ETC Group Excel to Google Fusion Table by Jim Lee", U: "https://www.google.com/fusiontables/data?docI=1NecyRN7xjFg6TA1YnRjPrEiYtoUKV2sWJ259GjY#rows:I=1", N: "Geoengineering Projects (ETC Group)"},
            { I: "p01", T: 'geojson', G: "/layers/geojson/weather-modification-association-projects-cv3d.geojson", MI: '/img/icons/rainy.png', S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/geoengineering/", N: "Weather Modification Association Projects"},
            { I: "p02", T: 'geojson', G: "/layers/geojson/noaa-weather-modification-projects-2012-cv3d.geojson", MI: '/img/icons/rainy.png', S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/geoengineering/", N: "NOAA 2012 Reported Activities (partial)"},
            { I: "p03", T: 'geojson', G: "/layers/geojson/ucar-eol-field-projects-cv3d.geojson", MI: '/img/icons/eol.gif', S: "National Center for Atmospheric Research (NCAR)/Earth Observing Laboratory (EOL)", U: "https://www.eol.ucar.edu/all-field-projects-and-deployments", N: "UCAR Earth Observing Lab Field Projects"}
        ]}
    },
    other: { N: "Other",
        basemaps: { N: "Base Maps", icon: "globe", '>': [
            { I: "World_Imagery", T: 'arcgis', G: "World_Imagery", S: "World Imagery provides one meter or better satellite and aerial imagery in many parts of the world and lower resolution satellite imagery worldwide. The map includes 15m TerraColor imagery at small and mid-scales (591M down to 72k) and 2.5m SPOT Imagery (288k to 72k) for the world, and USGS 15m Landsat imagery for Antarctica. The map features 0.3m resolution imagery in the continental United States and 0.6m resolution imagery in parts of Western Europe from Digital Globe. Recent 1m USDA NAIP imagery is available in select states of the US. In other parts of the world, 1 meter resolution imagery is available from GeoEye IKONOS, Getmapping, AeroGRID, IGN Spain, and IGP Portugal. Additionally, imagery at different resolutions has been contributed by the GIS User Community.", U: "http://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer", N: "ESRI World Imagery"},
            { I: "World_Street_Map", T: 'arcgis', G: "World_Street_Map", S: "This worldwide street map presents highway-level data for the world. Street-level data includes the United States; much of Canada; Mexico; Europe; Japan; Australia and New Zealand; India; South America and Central America; Africa; and most of the Middle East. This comprehensive street map includes highways, major roads, minor roads, one-way arrow indicators, railways, water features, administrative boundaries, cities, parks, and landmarks, overlaid on shaded relief imagery for added context. The map also includes building footprints for selected areas. Coverage is provided down to ~1:4k with ~1:1k and ~1:2k data available in select urban areas. The street map was developed by Esri using Esri basemap data, DeLorme basemap layers, U.S. Geological Survey (USGS) elevation data, Intact Forest Landscape (IFL) data for the world; HERE data for Europe, Australia and New Zealand, North America, South America and Central America, Africa, and most of the Middle East; OpenStreetMap contributors for select countries in Africa; MapmyIndia data in India; and select data from the GIS user community.", U: "http://server.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer", N: "ESRI World Street Map"},
            { I: "Ocean_Basemap", T: 'arcgis', G: "Ocean_Basemap", S: "This map is designed to be used as a base map by marine GIS professionals and as a reference map by anyone interested in ocean data. The base map includes bathymetry, marine water body names, undersea feature names, and derived depth values in meters. Land features include administrative boundaries, cities, inland waters, roads, overlaid on land cover and shaded relief imagery. The map was compiled from a variety of best available sources from several data providers, including General Bathymetric Chart of the Oceans GEBCO_08 Grid, IHO-IOC GEBCO Gazetteer of Undersea Feature Names, National Oceanic and Atmospheric Administration (NOAA), and National Geographic, DeLorme, NAVTEQ, Geonames.org, and Esri, and various other contributors. The base map currently provides coverage for the world down to a scale of ~1:577k, and coverage down to 1:72k in US coastal areas, and various other areas. Coverage down to ~ 1:9k is available limited areas based on regional hydrographic survey data. The base map was designed and developed by Esri. NOTE: Data from the GEBCO_08 grid shall not to be used for navigation or for any other purpose relating to safety at sea. The GEBCO_08 Grid is largely based on a database of ship-track soundings with interpolation between soundings guided by satellite-derived gravity data. In some areas, data from existing grids are included. The GEBCO_08 Grid does not contain detailed information in shallower water areas, information concerning the generation of the grid can be found on GEBCO's web site: http://www.gebco.net/data_and_products/gridded_bathymetry_data. The GEBCO_08 Grid is accompanied by a Source Identifier (SID) Grid which indicates which cells in the GEBCO_08 Grid are based on soundings or existing grids and which have been interpolated. The latest version of both grids and accompanying documentation is available to download, on behalf of GEBCO, from the British Oceanographic Data Centre (BODC) https://www.bodc.ac.uk/data/online_delivery/gebco. The names of the IHO (International Hydrographic Organization), IOC (intergovernmental Oceanographic Commission), GEBCO (General Bathymetric Chart of the Oceans), NERC (Natural Environment Research Council) or BODC (British Oceanographic Data Centre) may not be used in any way to imply, directly or otherwise, endorsement or support of either the Licensee or their mapping system.", U: "http://server.arcgisonline.com/arcgis/rest/services/World_Physical_Map/MapServer", N: "ESRI Oceans"},
            { I: "World_Physical_Map", T: 'arcgis', G: "World_Physical_Map", S: "This map presents the Natural Earth physical map at 1.24km per pixel for the world and 500m for the coterminous United States.", U: "http://server.arcgisonline.com/arcgis/rest/services/Ocean_Basemap/MapServer", N: "ESRI World Physical"},
            { I: "World_Shaded_Relief", T: 'arcgis', G: "World_Shaded_Relief", S: "This map portrays surface elevation as shaded relief. This map is used as a basemap layer to add shaded relief to other GIS maps, such as the ArcGIS Online World Street Map. It is especially useful in maps that do not contain orthoimagery. The map resolution (cell size) is as follows: 30 Meters for the U.S. 90 Meters for all land areas between 60° north and 56° south latitude. 1 KM resolution above 60° north and 56° south. The shaded relief imagery was developed by Esri using GTOPO30, Shuttle Radar Topography Mission (SRTM), and National Elevation Data (NED) data from the USGS.", U: "http://server.arcgisonline.com/arcgis/rest/services/World_Shaded_Relief/MapServer", N: "ESRI World Shaded Relief"},
            { I: "World_Topo_Map", T: 'arcgis', G: "World_Topo_Map", S: "This map is designed to be used as a basemap by GIS professionals and as a reference map by anyone. The map includes administrative boundaries, cities, water features, physiographic features, parks, landmarks, highways, roads, railways, and airports overlaid on land cover and shaded relief imagery for added context. The map provides coverage for the world down to a scale of ~1:72k. Coverage is provided down to ~1:4k for the following areas: Australia and New Zealand; India; Europe; Canada; Mexico; the continental United States and Hawaii; South America and Central America; Africa; and most of the Middle East. Coverage down to ~1:1k and ~1:2k is available in select urban areas. This basemap was compiled from a variety of best available sources from several data providers, including the U.S. Geological Survey (USGS), U.S. Environmental Protection Agency (EPA), U.S. National Park Service (NPS), Food and Agriculture Organization of the United Nations (FAO), Department of Natural Resources Canada (NRCAN), GeoBase, Agriculture and Agri-Food Canada, DeLorme, HERE, Esri, OpenStreetMap contributors, and the GIS User Community.", U: "http://server.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer", N: "ESRI World Topographic"},
            { I: "USA_Topo_Maps", T: 'arcgis', G: "USA_Topo_Maps", S: "This map presents land cover imagery for the world and detailed topographic maps for the United States. The map includes the National Park Service (NPS) Natural Earth physical map at 1.24km per pixel for the world at small scales, i-cubed eTOPO 1:250,000-scale maps for the contiguous United States at medium scales, and National Geographic TOPO! 1:100,000 and 1:24,000-scale maps (1:250,000 and 1:63,000 in Alaska) for the United States at large scales. The TOPO! maps are seamless, scanned images of United States Geological Survey (USGS) paper topographic maps.", U: "http://server.arcgisonline.com/arcgis/rest/services/USA_Topo_Maps/MapServer", N: "ESRI USA Topographic"},
            { I: "NatGeo_World_Map", T: 'arcgis', G: "NatGeo_World_Map", S: "This map is designed to be used as a general reference map for informational and educational purposes as well as a base map by GIS professionals and other users for creating web maps and web mapping applications. The map was developed by National Geographic and Esri and reflects the distinctive National Geographic cartographic style in a multi-scale reference map of the world. The map was authored using data from a variety of leading data providers, including DeLorme, HERE, UNEP-WCMC, NASA, ESA, USGS, and others. This reference map includes administrative boundaries, cities, protected areas, highways, roads, railways, water features, buildings and landmarks, overlaid on shaded relief and land cover imagery for added context. The map currently includes global coverage down to ~1:144k scale and more detailed coverage for North America down to ~1:9k scale.", U: "http://server.arcgisonline.com/arcgis/rest/services/NatGeo_World_Map/MapServer", N: "ESRI National Geographic"},
            { I: "bl-std", T: 'base-layer', G: "//stamen-tiles.a.ssl.fastly.net/toner/", S: "A high contrast black and white map. Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under CC BY SA.", U: "http://maps.stamen.com/", N: "Stamen Toner"},
            { I: "bl-stl", T: 'base-layer', G: "//stamen-tiles.a.ssl.fastly.net/toner-lite/", S: "A high contrast black and white map (light colored version). Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under CC BY SA.", U: "http://maps.stamen.com/", N: "Stamen Toner (Light)"},
            { I: "bl-swc", T: 'base-layer', G: "//stamen-tiles.a.ssl.fastly.net/watercolor/", S: "Reminiscent of hand drawn maps, Stamen watercolor maps apply raster effect area washes and organic edges over a paper texture to add warm pop to any map. Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under CC BY SA.", U: "http://maps.stamen.com/", N: "Stamen Watercolor"},
            { I: "bl-osm", T: 'base-layer', G: "//a.tile.openstreetmap.org/", S: "OpenStreetMap (OSM) is a collaborative project to create a free editable map of the world.", U: "http://www.openstreetmap.org", N: "OpenStreetMap (OSM)"},
            { I: "bl-mq", T: 'base-layer', G: "//otile1-s.mqcdn.com/tiles/1.0.0/osm/", S: "OpenStreetMap (OSM) is a collaborative project to create a free editable map of the world.", U: "http://www.openstreetmap.org", N: "MapQuest OpenStreetMap"}
        ]},
        electromagnetic: { N: "Electromagnetic", icon: "signal", '>': [
            { I: "star-wars", T: 'geojson', G: "/layers/geojson/star-wars-radar-cv3d.geojson", MI: '/img/icons/radar-black.png', S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/haarp/", N: "Missile Defense Radars (Star Wars)"},
            { I: "sky-heaters", T: 'geojson', G: "/layers/geojson/ionospheric-heaters-cv3d.geojson", MI: '/img/icons/radar-red.png', S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/haarp/", N: "Ionospheric Heaters"},
            { I: "haarp", Z: true, T: 'geojson', G: "/layers/geojson/haarp-cv3d.geojson", MI: '/img/icons/radar-ltblue.png', S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/haarp/", N: "High-Frequency Active Auroral Research Project (HAARP)"},
            { I: "superdarn", T: 'geojson', G: "/layers/geojson/superdarn-cv3d.geojson", MI: '/img/icons/radar-yellow.png', S: '<p>Created by <a href="http://climateviewer.com/rezn8d/">Jim Lee</a>.<br><br>The Super Dual Auroral Radar Network (SuperDARN) is an international radar network for studying the upper atmosphere and ionosphere, comprising eleven radars in the northern hemisphere and seven in the southern hemisphere that operate in the High Frequency (HF) bands between 8 and 22 MHz. The radars measure the Doppler velocity of plasma density irregularities in the ionosphere.<br><br>In their standard operating mode each radar scans through 16 beams of azimuthal separation 3.24°, with a total scan time of 1 min. Each beam is divided into 75 range gates of length 45 km, and so in each full scan the radars each cover 52° in azimuth and over 3000 km in range, an area of over 4×106 km².<br><br>SuperDARN began in 1983, when the first radar installation was constructed in Labrador, Canada. Source: <a href="http://en.wikipedia.org/wiki/Super_Dual_Auroral_Radar_Network" target="_blank">Wikipedia</a><br><a href="http://superdarn.jhuapl.edu/" target="_blank">John&#39;s Hopkins Applied Physics Lab</a><br><a href="http://sd-software.ece.vt.edu/tiki/tiki-print.php?page=VT%20SuperDARN%20Home" target="_blank">Virginia Tech SuperDARN</a><br><a href="http://cedarweb.hao.ucar.edu/wiki/index.php/Documents:Ground_Based_Instruments#B_-_Coherent_Ionospheric_Radars_.28.7E29.29" target="_blank">CEDAR: Ground Based Instruments</a><br><a href="http://articles.adsabs.harvard.edu//full/1995SSRv...71..761G/0000761.000.html" target="_blank">SuperDARN - A Global View of the Dynamics of High-Latitude Convection</a></p>', U: "http://superdarn.ece.vt.edu/tiki-index.php", N: "Super Dual Auroral Radar Network (SuperDARN)"},
            { I: "digisonde", T: 'geojson', G: "/layers/geojson/digisonde-cv3d.geojson", MI: '/img/icons/digisonde.png', S: "<p>Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br><br><a href='http://umlcar.uml.edu/stationlist.html'>Station List</a><br><br>Lowell Digisonde International manufactures and markets the Digisonde-Portable-Sounder-4D (DPS4D), the latest model in the DIGISONDE® series of advanced ionosondes built in Lowell since 1969. The Digisonde is an ionospheric radar that uses high-frequency radio waves for the remote sensing of the ionosphere, the ionosonde technology pioneered by Sir Edward Appleton in the late 1920s. DIGISONDE stands for “Digitally Integrating Goniometric IonoSONDE”. The DPS4D is the only commercially available ionosonde system that measures all parameters of the ionospherically reflected HF radio signals, and automatically calculates the local ionospheric electron density profile in real time.</p><img alt='Digisonde Network Map' src='http://www.digisonde.com/images/homepage-map.jpg' /><br><br>", U: "http://www.digisonde.com/", N: "DIGISONDE® Ionosonde Network"},
            { I: "elf-vlf", T: 'geojson', G: "/layers/geojson/elf-vlf-cv3d.geojson", MI: "/img/icons/rf-warning.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>Alpha RSDN-20, Beta Time Signal, LORAN-C, AWESOME VLF Network, Ground Wave Emergency Network (GWEN), and ELF transmission facilities.", U: "http://climateviewer.com/haarp/", N: "ELF and VLF Transmitters"},
            { I: "elf-vlf-ref", T: 'geojson', G: "/layers/geojson/elf-vlf-antennas-cv3d.geojson", MI: "/img/icons/antenna.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>Visual reference (Antennas) for the Alpha RSDN-20, Beta Time Signal, LORAN-C, AWESOME VLF Network, Ground Wave Emergency Network (GWEN), and ELF transmission facilities.", U: "http://climateviewer.com/haarp/", N: "ELF and VLF Visual Reference"},
            { I: "directed-energy", T: 'geojson', G: "/layers/geojson/xfiles-cv3d.geojson", MI: "/img/icons/laser.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/rezn8d/", N: "Lasers and Directed-Energy"},
            { I: "nexrad", T: 'geojson', G: "/layers/geojson/radar-nexrad-cv3d.geojson", MI: "/img/icons/doppler-green.png", S: '<p>Created by <a href="http://climateviewer.com/rezn8d/">Jim Lee</a>.<br><a href="http://radar.weather.gov/">radar.weather.gov</a><br><a href="http://www.roc.noaa.gov/WSR88D/About.aspx">WSR-88D Specifications</a><br><br>In 1988, the NEXRAD Agencies established the WSR-88D (Weather Surveillance Radar - 1988 Doppler) Radar Operations Center (ROC) in Norman, Oklahoma. The ROC employees come from the National Weather Service, Air Force, Navy, FAA, and support contractors. The ROC provides centralized meteorological, software, maintenance, and engineering support for all WSR-88D systems. WSR-88D systems will be modified and enhanced during their operational life to meet changing requirements, technology advances, and improved understanding of the application of these systems to real-time weather operations. The ROC also operates WSR-88D test systems for the development of hardware and software upgrades to enhance maintenance, operation, and provide new functionality.<br><br><img src="http://climateviewer.com/gallery/WSR88DCONUS.jpg" /></p>', U: "http://www.roc.noaa.gov/WSR88D/Program/NetworkSites.aspx", N: "NEXRAD Doppler Radar Stations"},
            { I: "sigmet", T: 'geojson', G: "/layers/geojson/radar-sigmet-cv3d.geojson", MI: "/img/icons/doppler-green.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br><p>The Canadian weather radar network consists of 31 weather radars spanning Canada's most populated regions. Their primary purpose is the early detection of precipitation, its motion and the threat it poses to life and property. Each has a range of 256 km (159 mi) in radius around the site to detect reflectivity, and a range of 128 km (80 mi) for detecting velocity patterns (Doppler effect).</p><p><img src='http://climateviewer.com/gallery/canrad.png' /></p>", U: "http://weather.gc.ca/radar/index_e.html", N: "Canadian Sigmet Doppler Radar Stations"},
            { I: "tdwr", T: 'geojson', G: "/layers/geojson/radar-tdwr-cv3d.geojson", MI: "/img/icons/doppler-yellow.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>The Terminal Doppler Weather Radar (TDWR) network is a Doppler weather radar system used primarily for the detection of hazardous wind shear conditions, precipitation, and winds aloft on and near major airports situated in climates with great exposure to thunderstorms in the United States. NCEI archives the derived products (called Level III), which are in the same data format as Next Generation Weather Radar (NEXRAD) Level III. NCEI does not archive the base data (called Level II).", U: "https://www.ncdc.noaa.gov/data-access/radar-data/tdwr", N: "Terminal Doppler Weather Radar (TDWR) Stations"},
            { I: "jss", T: 'geojson', G: "/layers/geojson/radar-jss-cv3d.geojson", MI: "/img/icons/doppler-red.png", S: '<p>Created by <a href="http://climateviewer.com/rezn8d/">Jim Lee</a>.<br>The JSS is a joint United States Air Force and Federal Aviation Administration system for the atmospheric air defense of North America. It replaced the Semi Automatic Ground Environment (SAGE) system in 1983.<br><br>The JSS consists of long range surveillance radars, primarily operated and maintained by the Federal Aviation Administration (FAA), but providing communication and radar data to both FAA and United States Air Force control centers.</p><h3>Air Route Surveillance Radar (ARSR)</h3><p>FAA equipment is a primarily a mixture of Long Range Air Route Surveillance Radars (ARSR) of various types, although some use legacy AN/FPS radars. They are co-located with UHF ground-air-ground (G/A/G) transmitter/receiver (GATR) facilities at many locations. Fourteen sites have VHF radios as well. The GATR facility provides radio access to fighters and Airborne early warning and control (AEW&C) aircraft from the SOCCs. The JSS has been enhanced under the FAA/Air Force Radar Replacement Program with 44 ARSR-4/FPS-130 radars to replace some of the many previous long-range radars. This provides common, high-performance, unattended radars. The ARSR-4/FPS-130 is a 3-D long range radar with an effective detection range of some 250 miles and has been fully integrated with JSS at all joint use sites.<br /><br />These radars are generally unattended except for periodic FAA maintenance crews which visit the sites as necessary.<br>Source: <a href="http://en.wikipedia.org/wiki/Joint_Surveillance_System">Joint Surveillance System Wikipedia</a><br><br><a href="https://www.fas.org/nuke/guide/usa/airdef/arsr-4.htm">ARSR-4 Reference FAS.org</a><br><br><a href="http://climateviewer.com/gallery/joint_surveillance_system_doppler.jpg" target="_blank">View large photo of JSS Doppler Station</a><br><br><img src="http://climateviewer.com/gallery/arsrinst.jpg" /><img src="http://climateviewer.com/gallery/Conr-afnorth-emblem.jpg"/><br><br><img src="http://climateviewer.com/gallery/Air_Defense_Command.png"/></p>', U: "http://climateviewer.com/rezn8d/", N: "Joint Surveillance System (JSS), FAA Long-range Radar Stations"},
            { I: "ioos", T: 'geojson', G: "/layers/geojson/radar-ioos-cv3d.geojson", MI: "/img/icons/doppler-blue.png", S: 'Created by <a href="http://climateviewer.com/rezn8d/">Jim Lee</a>.<br><p>High frequency (HF) radar systems measure the speed and direction of ocean surface currents in near real time. Currents in the ocean are equivalent to winds in the atmosphere because they move things from one location to another. These currents carry nutrients as well as pollutants, so it is important to know the currents for ecological and economic reasons. The currents carry any floating object, which is why U.S. Coast Guard search and rescue operators use HF radar data to make critical decisions when rescuing disabled vessels and people stranded in the water.</p><p>These radars can measure currents over a large region of the coastal ocean, from a few kilometers offshore up to 200 km, and can operate under any weather conditions. They are located near the water’s edge, and need not be situated atop a high point of land.  Traditionally, crews placed current measuring devices directly into the water to retrieve current speeds.  While these direct measurement systems are still widely used as a standard reference, HF radars are the only sensors that can measure large areas at once with the detail required for the important applications described here.  Not even satellites have this capability.</p><p><img src="http://climateviewer.com/gallery/hfr_anthen240.jpg" /></p>', U: "http://www.ioos.noaa.gov/hfradar/welcome.html", N: "Integrated Ocean Observing System (IOOS) Radar Stations"},
            { I: "npn-wind-radar", T: 'geojson', G: "/layers/geojson/npn-wind-radar-cv3d.geojson", MI: "/img/icons/radar-pink.png", S: "<p>Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>Wind profilers are specifically designed to measure vertical profiles of horizontal wind speed and direction from near the surface to above the tropopause. Data from this network are distributed in real-time to government and university atmospheric researchers, private meteorologists, the National Centers for Environmental Prediction, the Storm Prediction Center, all National Weather Service (NWS) Forecast Offices, and foreign agencies responsible for weather prediction.</p>", U: "http://www.profiler.noaa.gov/npn/npnSiteLocationsAsText.jsp", N: "NOAA Profiler Network (NPN) Wind Radar"},
            { I: "madis-wind-radar", T: 'geojson', G: "/layers/geojson/madis-cap-wind-radar-cv3d.geojson", MI: "/img/icons/radar-purple.png", S: "<p>Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>Cooperative Agency Profilers (CAP) is a cooperative venture between GSD (formerly FSL) and many participating agencies enabling GSD to; acquire profiler and RASS data in near real-time, apply GSD's data quality control algorithms, and make these value-added data available on the web and to the National Weather Service. At this time, data from approximately 100 CAP sites from over 35 different agencies from around the world are being acquired by GSD. The majority of CAP systems are 915 MHz Boundary Layer Profilers, there are also several 449 MHz and 50 MHz profilers in the CAP network.</p>", U: "https://madis-data.noaa.gov/cap/", N: "MADIS CAP Wind Radar"},
            { I: "aeronet", T: 'geojson', G: "/layers/geojson/aeronet-cv3d.geojson", MI: "/img/icons/nasa.png", S: "<p>Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>The AERONET (AErosol RObotic NETwork) program is a federation of ground-based remote sensing aerosol networks established by NASA and PHOTONS (Univ. of Lille 1, CNES, and CNRS-INSU) and is greatly expanded by collaborators from national agencies, institutes, universities, individual scientists, and partners. The program provides a long-term, continuous and readily accessible public domain database of aerosol optical, microphysical and radiative properties for aerosol research and characterization, validation of satellite retrievals, and synergism with other databases. The network imposes standardization of instruments, calibration, processing and distribution.</p>", U: "http://aeronet.gsfc.nasa.gov/", N: "AERONET (AErosol RObotic NETwork)"},
            { I: "bsrn", T: 'geojson', G: "/layers/geojson/bsrn-cv3d.geojson", MI: "/img/icons/partly_cloudy.png", S: "<p>Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>It is believed that the radiation budget of the Earth-atmosphere system plays a fundamental role in determining the thermal conditions and the circulation of the atmosphere and the ocean, shaping the main characteristics of the Earth's climate. The irradiances at the Earth's surface are especially important in understanding the climate processes, since the Earth's surface transforms approximately 60% of the solar radiation absorbed by the planet. These irradiances also occupy an important position in the ocean surface energy budget, ultimately influencing the major features of ocean currents.</p><p>While a small change in irradiance at the Earth's surface may cause a profound change in climate, the existing radiometric network is not capable of arriving at the required accuracy for climate research. In fact our present understanding of the radiation distribution both - horizontally and vertically - is not sufficient to understand the present climate. The simulation of the past and future climate changes, which would be induced by the change in radiation, is even more uncertain.</p><p>This was the background for the World Climate Research Programme (WCRP) Radiative Fluxes Working Group to initiate a new Baseline Surface Radiation Network (BSRN) to support the research projects of the WCRP and other scientific programs. Some years later the BSRN incorporated into the WCRP Global Energy and Water Cycle Experiment (GEWEX) Radiation Panel.</p>", U: "http://www.bsrn.awi.de/", N: "Baseline Surface Radiation Network (BSRN)"},
            { I: "esrl", T: 'geojson', G: "/layers/geojson/esrl-cv3d.geojson", MI: "/img/icons/noaa.gif", S: "<p>Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>NOAA Earth Systems Research Lab (ESRL). ESRL was formed to pursue a broad and comprehensive understanding of the Earth system. This system comprises many physical, chemical and biological processes that need to be dynamically integrated to better predict their behavior over scales from local to global and periods of minutes to millennia.</p>", U: "http://www.esrl.noaa.gov/psd/data/obs/sites/", N: "Earth Systems Research Lab (ESRL) Instruments"},
            { I: "doris", T: 'geojson', G: "/layers/geojson/doris-cv3d.geojson", MI: "/img/icons/ids.png", S: "<p>Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.<br>DORIS is a Doppler satellite tracking system developped for precise orbit determination and precise ground location. It is onboard the Cryosat-2, Jason-1, Jason-2, ENVISAT and HY-2A altimetric satellites and the remote sensing satellites SPOT-4 and SPOT-5. It also flew with SPOT-2, SPOT-3 and TOPEX/POSEIDON.</p><p>IDS is an international service which provides a support, through DORIS data and products, to geodetic, geophysical, and other research and operational activities. New proposals for Analysis Centers and temporary or permanent DORIS stations are welcome.</p>", U: "http://Is-doris.org/network/googleearth.html", N: "DORIS (Doppler Orbitography and Radiopositioning Integrated by Satellite)"},
            { I: "f16", T: 'geojson', G: "/layers/geojson/atmospheric-observatories-cv3d.geojson", MI: "/img/icons/radar-dish.png", S: "Created by <a href='http://climateviewer.com/rezn8d/'>Jim Lee</a>.", U: "http://climateviewer.com/rezn8d/", N: "Other Radars, Observatories, Telescope Arrays, Satellite Communications"},
            { H: true, I: "f17", T: 'geojson', G: "/layers/geojson/FCC-cell-towers-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. Cellular (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "Cell Phone Towers (USA FCC)"},
            { H: true, I: "f24", T: 'geojson', G: "/layers/geojson/FCC-paging-towers-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. Paging (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "Paging Towers (USA FCC)"},
            { H: true, I: "f18", T: 'geojson', G: "/layers/geojson/FCC-AM-radio-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. AM (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "AM Radio (USA FCC)"},
            { H: true, I: "f19", T: 'geojson', G: "/layers/geojson/FCC-FM-radio-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. FM (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "FM Radio (USA FCC)"},
            { H: true, I: "f20", T: 'geojson', G: "/layers/geojson/FCC-Digital-TV-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. TV - Digital (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "Digital Television (USA FCC)"},
            { H: true, I: "f21", T: 'geojson', G: "/layers/geojson/FCC-NTSC-TV-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. TV - NTSC (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "NTSC Television (USA FCC)"},
            { H: true, I: "f22", T: 'geojson', G: "/layers/geojson/FCC-LM-broadcast-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. Land Mobile - Broadcast (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "Land Mobile Broadcast (USA FCC)"},
            { H: true, I: "f23", T: 'geojson', G: "/layers/geojson/FCC-BRS-EBS-2012-cv3d.geojson", MI: "http://climateviewer.com/gallery/radioz.png", S: "Federal Communications Commission (FCC) Licensing Database Extracts. BRS/EBS (zip) (06-14-2012) .SHP file to GeoJSON conversion by Jim Lee", U: "http://web.archive.org/web/20140522193524/http://wireless.fcc.gov/geographic/index.htm?job=licensing_database_extracts", N: "Educational Broadcast (BRS/EBS) (USA FCC)"}
        ]},
        flight: { N: "Flight", icon: "plane", '>': [
            { I: "us_runways", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "us_runways", S: "NOAA Ocean Service's nowCOAST's Map Services - Locations/Footprints of U.S. Airport Runways", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "U.S. Airport Runways"},
            { I: "artcc", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "artcc", S: "NOAA Ocean Service's nowCOAST's Map Services - Air Route Traffic Control Centers - Areas of Responsibility", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "Air Route Traffic Control Center Boundaries"}
        ]},
        boats: { N: "Marine Traffic", icon: "anchor", '>': [
            { P: true, I: "kml-noaabuoy", T: 'kml', G: "http://www.ndbc.noaa.gov/kml/marineobs_as_kml.php?sort=owner", S: "National Oceanic and Atmospheric Administration (NOAA) National Data Buoy Center", U: "http://www.ndbc.noaa.gov/", N: "NOAA Buoy Tracker"},
            { P: true, I: "kml-noaaship", T: 'kml', G: "http://egisws02.nos.noaa.gov/shiptracker/kml/All_Ships_CL.kmz", S: "National Oceanic and Atmospheric Administration (NOAA)", U: "http://egisws02.nos.noaa.gov/shiptracker/", N: "NOAA Ship Tracker"}
        ]},
        geographic: { N: "Geographic", icon: "info sign", '>': [
            { I: "pyramids", T: 'kml', G: "/layers/kml/3rdparty/other/Pyramids-FR-CV3D.kmz", S: "based on the film &quot;Revelations of the PyramIs&quot;", U: "http://www.youtube.com/watch?v=GhC6lhAD4xY", N: "Pyramids of the World"},
            { I: "world_rivers", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "world_rivers", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "World Rivers"},
            { I: "world_lakes", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "world_lakes", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "World Lakes"},
            { I: "great_lakes", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "great_lakes", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "World Great Lakes"},
            { I: "rivers", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "rivers", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "U.S. Rivers"},
            { I: "lakes", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "lakes", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "U.S. Lakes"},
            { I: "watersheds", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "watersheds", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "U.S. Watershed Boundaries"}
        ]},
        economic: { N: "Economic", icon: "money", '>': [
            { I: "native-american1", Z: true, T: 'kml', G: "/layers/kml/3rdparty/other/Indian-Lands.kmz", S: "This map layer shows Indian lands of the United States. Only areas of 640 acres or more are included. Federally-administered lands within a reservation are included for continuity; these may or may not be consIered part of the reservation and are simply described with their feature type and the administrating Federal agency. This is an updated version of the December 2005 map layer.", U: "http://nationalatlas.gov/atlasftp.html#indlanp", N: "Native American Lands 2005" },
            { I: "urban_areas_fill", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "urban_areas_fill", S: "NOAA Ocean Service's nowCOAST's Map Services - U.S. Urban Area Boundaries (color-filled polygons)", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "U.S. Urban Areas"},
            { I: "eez", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "eez", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "U.S. Exclusive Economic Zone Boundaries"},
            { I: "world_countries", T: 'wms', G: "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs", L: "world_countries", S: "NOAA Ocean Service's nowCOAST's Map Services", U: "http://nowcoast.noaa.gov/help/mapservices.shtml", N: "World Country Boundaries"}
        ]}
    }
};

